CREATE TABLE [dbo].[Flight_detail] (
    [bookingid]              NVARCHAR (50)  NULL,
    [departure_code]         NVARCHAR (50)  NULL,
    [departure_name]         NVARCHAR (300) NULL,
    [departure_city]         NVARCHAR (300) NULL,
    [departure_datetime]     DATETIME       NULL,
    [arrival_code]           NVARCHAR (50)  NULL,
    [arrival_name]           NVARCHAR (300) NULL,
    [arrival_city]           NVARCHAR (300) NULL,
    [arrival_datetime]       DATETIME       NULL,
    [operating_airline_code] NVARCHAR (50)  NULL,
    [operating_airline_name] NVARCHAR (300) NULL,
    [flightnumber]           NVARCHAR (50)  NULL,
    [equipment]              NVARCHAR (50)  NULL,
    [cabin_class_code]       NVARCHAR (50)  NULL,
    [cabin_class_text]       NVARCHAR (300) NULL,
    [flighttime]             NVARCHAR (50)  NULL,
    [flightminute]           NVARCHAR (50)  NULL,
    [marketing_airline_code] NVARCHAR (50)  NULL,
    [marketing_airline_name] NVARCHAR (50)  NULL,
    [connectiontime]         NVARCHAR (300) NULL,
    [resbooking_code]        NVARCHAR (50)  NULL,
    [resbooking_text]        NVARCHAR (300) NULL,
    [api_segmentid]          NVARCHAR (50)  NULL,
    [id]                     INT            IDENTITY (1, 1) NOT NULL,
    [DepartureTerminal]      NVARCHAR (300) NULL,
    [ArrivalTerminal]        NVARCHAR (300) NULL,
    [technicalStopminute]    NVARCHAR (300) NULL
);

