CREATE TABLE [dbo].[Flight_booking] (
    [id]                       INT             IDENTITY (10000, 1) NOT NULL,
    [departure_code]           NVARCHAR (100)  NULL,
    [departure_city]           NVARCHAR (300)  NULL,
    [departure_name]           NVARCHAR (900)  NULL,
    [departure_datetime]       DATETIME        NULL,
    [arrival_code]             NVARCHAR (300)  NULL,
    [arrival_city]             NVARCHAR (300)  NULL,
    [arrival_name]             NVARCHAR (900)  NULL,
    [arrival_datetime]         DATETIME        NULL,
    [system_payment_reference] NVARCHAR (MAX)  NULL,
    [triptype]                 NVARCHAR (300)  NULL,
    [faretype]                 NVARCHAR (300)  NULL,
    [searchcode]               NVARCHAR (MAX)  NULL,
    [userid]                   INT             NULL,
    [api_currency]             NVARCHAR (300)  NULL,
    [api_baseprice]            DECIMAL (18, 2) NULL,
    [api_totalprice]           DECIMAL (18, 2) NULL,
    [api_taxprice]             DECIMAL (18, 2) NULL,
    [baseprice]                DECIMAL (18, 2) NULL,
    [totalprice]               DECIMAL (18, 2) NULL,
    [taxprice]                 DECIMAL (18, 2) NULL,
    [extraserviceprice]        DECIMAL (18, 2) NULL,
    [total_adult]              INT             NULL,
    [total_child]              INT             NULL,
    [total_infant]             INT             NULL,
    [api_faresourcecode]       NVARCHAR (MAX)  NULL,
    [system_faresourcecode]    NVARCHAR (MAX)  NULL,
    [system_searchcode]        NVARCHAR (MAX)  NULL,
    [system_reference]         NVARCHAR (MAX)  NULL,
    [phone_country_code]       NVARCHAR (300)  NULL,
    [phone_number]             NVARCHAR (300)  NULL,
    [email]                    NVARCHAR (500)  NULL,
    [status]                   INT             NULL,
    [HoldAllowed]              BIT             NULL,
    [IsRefundable]             BIT             NULL,
    [createddate]              DATETIME        NULL,
    [paymenttype]              INT             NULL,
    [api_extraserviceprice]    DECIMAL (18, 2) NULL,
    [api_tkt_time_limit]       NVARCHAR (500)  NULL,
    [api_SecurityToken]        NVARCHAR (MAX)  NULL,
    [api_SessionId]            NVARCHAR (MAX)  NULL,
    [is_lcc_airline]           BIT             NULL,
    [paymentstatus]            INT             NULL,
    [searchchanel]             INT             NULL,
    [ipaddress]                NVARCHAR (300)  NULL,
    [pcc]                      NVARCHAR (300)  NULL,
    [supplier]                 INT             NULL,
    [PNR]                      NVARCHAR (400)  NULL
);

